# Generated by Django 4.2.7 on 2023-12-17 09:10

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
