# Generated by Django 4.2.7 on 2023-12-17 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_employee_gender_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
